name: imdb
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^4.1.1
  http: ^0.12.0
  rxdart: ^0.20.0
  bloc_pattern: ^1.3.0
  flutter_launcher_icons: ^0.7.4
  cached_network_image: ^1.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/icons/icon-710x599-android.png"
  image_path_ios: "assets/icons/icon-710x599-ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  
flutter:
  uses-material-design: true
  assets:
   - assets/